server:
  port: 8888
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://172.0.66.18:33066/scraping?useSSL=false
  web:
    resources:
      static-locations: file:/Volumes/Lee/Code/github/file-system-demo/files/
  mvc:
    static-path-pattern: /image/**
file:
  base-path: /Volumes/Lee/Code/github/file-system-demo/files/
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # ?????????sql?????????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.rookie.pojo
  #??xml???
  mapper-locations: classpath*:/dao/*.xml

